### ISSUE TITLE
0.5s throttling works incorrectly

### ISSUE THREAD

**Issue by ksloginov** [ektemfg/GoogleTranslat0r#5]
**Expected/Technical details:** While editing text, do an "on-the-fly" translation of the current input, but with 0.5s throttling. I.e. user types "E" -> the app waits for 0.5s and does the translation. Then the user types "En", and immediately types "Engl". Make sure the app is not doing the translation for the "En".

**Actual:** There's a syntax issue in the code. As a result, the translation still happens, if the user keeps typing.
(You can experiment by keep typing back and forth non-stop. There suppose to be no network requests before you stop)

**Comment by ektemfg** [comment]
Thank you for your feedback, @ksloginov. 

I appreciate you bringing this issue to my attention and will prioritize fixing the "on-the-fly" translation feature throttling  in the next sprint. 
Thank you for your valuable feedback and I will continue to work hard to improve our product.

Best regards,
Dimitrije

**Comment by ektemfg** [comment]
Dear, @ksloginov.
I am pleased to inform you that the fix for the "on-the-fly" translation feature throttling is now ready and will be pushed to the repository after it has been reviewed and tested by our team. 

https://user-images.githubusercontent.com/99316570/207758749-bd21a4e6-71d9-4d7f-9a04-c7e57831bdf2.mov

Thank you!
